import "./globals.css";
import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";

import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";

const font = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "NFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-black", font.className)}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
